# Generated by Django 3.0.7 on 2020-06-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=70)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
